// Generated by scripts/optimize-images.mjs — do not edit by hand.
export const images = {
  "tarun-portrait": {
    "src": "/images/tarun-portrait-490.webp",
    "srcSet": "/images/tarun-portrait-490.webp 490w",
    "width": 490,
    "height": 750
  },
  "tarun-google": {
    "src": "/images/tarun-google-720.webp",
    "srcSet": "/images/tarun-google-720.webp 720w, /images/tarun-google-1108.webp 1108w",
    "width": 1108,
    "height": 1478
  },
  "speaking-motilal": {
    "src": "/images/speaking-motilal-800.webp",
    "srcSet": "/images/speaking-motilal-800.webp 800w, /images/speaking-motilal-1600.webp 1600w",
    "width": 1600,
    "height": 1293
  },
  "stage-keynote": {
    "src": "/images/stage-keynote-800.webp",
    "srcSet": "/images/stage-keynote-800.webp 800w, /images/stage-keynote-1460.webp 1460w",
    "width": 1460,
    "height": 800
  },
  "consultation-table": {
    "src": "/images/consultation-table-800.webp",
    "srcSet": "/images/consultation-table-800.webp 800w, /images/consultation-table-1460.webp 1460w",
    "width": 1460,
    "height": 800
  },
  "consultation-office": {
    "src": "/images/consultation-office-800.webp",
    "srcSet": "/images/consultation-office-800.webp 800w, /images/consultation-office-1460.webp 1460w",
    "width": 1460,
    "height": 800
  },
  "community-meetup": {
    "src": "/images/community-meetup-800.webp",
    "srcSet": "/images/community-meetup-800.webp 800w, /images/community-meetup-1101.webp 1101w",
    "width": 1101,
    "height": 627
  },
  "avatar-ram-raju": {
    "src": "/images/avatar-ram-raju-160.webp",
    "srcSet": "/images/avatar-ram-raju-160.webp 160w",
    "width": 160,
    "height": 160
  },
  "avatar-shailesh-benedict": {
    "src": "/images/avatar-shailesh-benedict-160.webp",
    "srcSet": "/images/avatar-shailesh-benedict-160.webp 160w",
    "width": 160,
    "height": 160
  },
  "avatar-shivani-sahay": {
    "src": "/images/avatar-shivani-sahay-160.webp",
    "srcSet": "/images/avatar-shivani-sahay-160.webp 160w",
    "width": 160,
    "height": 160
  },
  "insight-linkedin": {
    "src": "/images/insight-linkedin-720.webp",
    "srcSet": "/images/insight-linkedin-720.webp 720w",
    "width": 720,
    "height": 407
  },
  "insight-instagram": {
    "src": "/images/insight-instagram-720.webp",
    "srcSet": "/images/insight-instagram-720.webp 720w",
    "width": 720,
    "height": 407
  },
  "insight-creator": {
    "src": "/images/insight-creator-720.webp",
    "srcSet": "/images/insight-creator-720.webp 720w",
    "width": 720,
    "height": 407
  },
  "insight-whatsapp": {
    "src": "/images/insight-whatsapp-720.webp",
    "srcSet": "/images/insight-whatsapp-720.webp 720w",
    "width": 720,
    "height": 407
  },
  "insight-podcast": {
    "src": "/images/insight-podcast-720.webp",
    "srcSet": "/images/insight-podcast-720.webp 720w",
    "width": 720,
    "height": 407
  },
  "insight-digital-marketing": {
    "src": "/images/insight-digital-marketing-720.webp",
    "srcSet": "/images/insight-digital-marketing-720.webp 720w",
    "width": 720,
    "height": 407
  },
  "insight-campaigns": {
    "src": "/images/insight-campaigns-720.webp",
    "srcSet": "/images/insight-campaigns-720.webp 720w",
    "width": 720,
    "height": 402
  },
  "insight-ai-tools": {
    "src": "/images/insight-ai-tools-720.webp",
    "srcSet": "/images/insight-ai-tools-720.webp 720w",
    "width": 720,
    "height": 402
  },
  "insight-marketing-trends": {
    "src": "/images/insight-marketing-trends-720.webp",
    "srcSet": "/images/insight-marketing-trends-720.webp 720w",
    "width": 720,
    "height": 407
  }
} as const

export type ImageName = keyof typeof images
