// Downloads Tarun's photography from tarunmakhija.in, crops away baked-in frames, and writes
// responsive WebP files to public/images plus a typed manifest at src/data/images.generated.ts.
// Run with: npm run images
import { mkdir, writeFile } from 'node:fs/promises'
import sharp from 'sharp'

const SOURCE = 'https://tarunmakhija.in/wp-content/uploads/'
const OUT_DIR = new URL('../public/images/', import.meta.url)
const MANIFEST = new URL('../src/data/images.generated.ts', import.meta.url)

// crop: [left, top, width, height] in source pixels. square: centre-crop to a square.
const sources = [
  { name: 'tarun-portrait', path: '2023/07/Blog-Newsletter.jpg', crop: [484, 28, 490, 750], widths: [490] },
  { name: 'tarun-google', path: '2023/04/Google.jpg', widths: [720, 1200] },
  { name: 'speaking-motilal', path: '2023/04/IMG_2114-scaled-e1680698754490.jpg', widths: [800, 1600] },
  { name: 'stage-keynote', path: '2023/08/Tarun-V3-website-2.png', crop: [70, 50, 1460, 800], widths: [800, 1460] },
  { name: 'consultation-table', path: '2023/08/Tarun-V3-website-3.png', crop: [70, 50, 1460, 800], widths: [800, 1460] },
  { name: 'consultation-office', path: '2023/08/Tarun-V3-website-4.png', crop: [70, 50, 1460, 800], widths: [800, 1460] },
  { name: 'community-meetup', path: '2023/04/1.png', widths: [800, 1600] },
  { name: 'avatar-ram-raju', path: '2023/06/B4C3F021-7F0D-4F16-9602-3A6B78AAD79D.jpeg', square: true, widths: [160] },
  { name: 'avatar-shailesh-benedict', path: '2023/06/A338C781-4A5F-42E7-BCDA-E84DFA9AE14D.jpeg', square: true, widths: [160] },
  { name: 'avatar-shivani-sahay', path: '2023/06/F4AD0A6C-7992-42F9-AF36-D5B4B4C590A8.jpeg', square: true, widths: [160] },
  { name: 'insight-linkedin', path: '2025/04/LinkedIn.jpg', widths: [720] },
  { name: 'insight-instagram', path: '2025/04/Instagram.jpg', widths: [720] },
  { name: 'insight-creator', path: '2025/04/Creator.jpg', widths: [720] },
  { name: 'insight-whatsapp', path: '2025/04/Whatsapp-Marketing.jpg', widths: [720] },
  { name: 'insight-podcast', path: '2025/04/Podcast.jpg', widths: [720] },
  { name: 'insight-digital-marketing', path: '2025/04/Digital-Marketing.jpg', widths: [720] },
  { name: 'insight-campaigns', path: '2025/02/Campaigns.jpg', widths: [720] },
  { name: 'insight-ai-tools', path: '2025/02/AI-tools.jpg', widths: [720] },
  { name: 'insight-marketing-trends', path: '2025/02/Digital-Marketing-Trends.jpg', widths: [720] },
]

await mkdir(OUT_DIR, { recursive: true })
const manifest = {}

for (const { name, path, crop, square, widths } of sources) {
  const response = await fetch(SOURCE + path, { headers: { 'User-Agent': 'Mozilla/5.0' } })
  if (!response.ok) throw new Error(`${response.status} for ${path}`)
  let base = sharp(Buffer.from(await response.arrayBuffer())).rotate()
  if (crop) base = base.extract({ left: crop[0], top: crop[1], width: crop[2], height: crop[3] })
  if (square) base = base.resize(widths[0], widths[0], { fit: 'cover', position: 'attention' })
  const master = await base.toBuffer()
  const { width: masterWidth, height: masterHeight } = await sharp(master).metadata()

  const outputs = []
  for (const width of widths) {
    const target = Math.min(width, masterWidth)
    const file = `${name}-${target}.webp`
    const info = await sharp(master).resize({ width: target, withoutEnlargement: true }).webp({ quality: 78, effort: 6 }).toFile(new URL(file, OUT_DIR).pathname.replace(/^\/([A-Za-z]:)/, '$1'))
    outputs.push({ file, width: info.width, size: info.size })
  }

  const largest = outputs.at(-1)
  manifest[name] = {
    src: `/images/${outputs[0].file}`,
    srcSet: outputs.map(({ file, width }) => `/images/${file} ${width}w`).join(', '),
    width: largest.width,
    height: Math.round((largest.width / masterWidth) * masterHeight),
  }
  console.log(name.padEnd(28), outputs.map(({ file, size }) => `${file} ${(size / 1024).toFixed(0)}KB`).join('  '))
}

await writeFile(MANIFEST, `// Generated by scripts/optimize-images.mjs — do not edit by hand.\nexport const images = ${JSON.stringify(manifest, null, 2)} as const\n\nexport type ImageName = keyof typeof images\n`)
